version: "3.9"
services:
  backend: 
    build: .
    ports:
      - "8888:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db: 
    # platform: linux/x86_64 if using m1 chip mac
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"